services:
  mongo:
    image: mongo:6
    container_name: fastfood-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    attach: false

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastfood-backend
    restart: no
    ports:
      - "5050:5050"
      - "9229:9229" 
    env_file:
      - ./.env
    depends_on:
      - mongo
    volumes:
      - ./:/app
    working_dir: /app

volumes:
  mongodb-data:
